version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB=${POSTGRES_DB}
      POSTGRES_USER=${POSTGRES_USER}
      POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      -postgres_data:/var/lib/postgresql/data



  http-server:
    build:
      context: ./
      dockerfile: dockerfile/Dockerfile.client_fe
    ports:
    - "3004:3004"
    environment:
      DATABASE_URL:${DATABASE_URL}
    depends_on:
      - db

  ws-server:
    build:
      context: ./
      dockerfile: dockerfile/Dockerfile.ws-server
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
  
  client_fe:
    build:
      context: ./
      dockerfile: dockerfile/Dockerfile.client_fe
    ports:
      -"3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
volumes:
postgres_data: