FROM node:18-alpine

RUN corepack enable


WORKDIR /user/src/app



COPY package.json pnpm-lock.yaml ./
COPY turbo.json ./
COPY packages/db/package.json ./packages/db/
COPY apps/http-server/package.json ./apps/http-server/

# Install dependencies
RUN pnpm install --filter=http-server...

# Copy source files
COPY packages/db ./packages/db
COPY apps/http-server ./apps/http-server

# Generate Prisma client
WORKDIR /user/src/app/packages/db
RUN pnpm install
RUN npx prisma generate

# Build the application
WORKDIR /user/src/app
RUN pnpm run build --filter=http-server

CMD [ "pnpm " ,"start:http-server","--filter=http-server" ]
